export const LANGUAGES = [
  { code: "vi", name: "Tiếng Việt (Vietnamese)" },
  { code: "en", name: "English (English)" },
  {
    code: "yue-Hant",
    name: "廣東話（繁體） (Chinese, Cantonese (Traditional))",
  },
  {
    code: "zh",
    name: "普通话（简体中文） (Chinese, Mandarin (Simplified))",
  },
  {
    code: "zh-Hant",
    name: "國語（繁體中文） (Chinese, Mandarin (Traditional))",
  },
  { code: "ja", name: "日本語 (Japanese)" },
  { code: "ko", name: "한국어 (Korean)" },
  { code: "es", name: "Español (Spanish)" },
  { code: "fr", name: "Français (French)" },
  { code: "de", name: "Deutsch (German)" },
  { code: "pt", name: "Português (Portuguese)" },
  { code: "ru", name: "Русский (Russian)" },
  { code: "ar", name: "العربية (Arabic)" },
  { code: "hi", name: "हिन्दी (Hindi)" },
  { code: "it", name: "Italiano (Italian)" },
  { code: "th", name: "ไทย (Thai)" },
  { code: "mn", name: "Монгол (Mongolian)" },
  { code: "my", name: "မြန်မာ (Burmese)" },
  { code: "id", name: "Bahasa Indonesia (Indonesian)" },
  { code: "nl", name: "Nederlands (Dutch)" },
  { code: "pl", name: "Polski (Polish)" },
  { code: "tr", name: "Türkçe (Turkish)" },
  { code: "bn", name: "বাংলা (Bengali)" },
  { code: "ur", name: "اردو (Urdu)" },
  { code: "ms", name: "Bahasa Melayu (Malay)" },
  { code: "fil", name: "Filipino (Filipino)" },
  { code: "ta", name: "தமிழ் (Tamil)" },
  { code: "te", name: "తెలుగు (Telugu)" },
  { code: "mr", name: "मराठी (Marathi)" },
  { code: "gu", name: "ગુજરાતી (Gujarati)" },
  { code: "pa", name: "ਪੰਜਾਬੀ (Punjabi)" },
  { code: "uk", name: "Українська (Ukrainian)" },
  { code: "cs", name: "Čeština (Czech)" },
  { code: "ro", name: "Română (Romanian)" },
  { code: "hu", name: "Magyar (Hungarian)" },
  { code: "el", name: "Ελληνικά (Greek)" },
  { code: "sv", name: "Svenska (Swedish)" },
  { code: "da", name: "Dansk (Danish)" },
  { code: "no", name: "Norsk (Norwegian)" },
  { code: "fi", name: "Suomi (Finnish)" },
  { code: "he", name: "עברית (Hebrew)" },
  { code: "fa", name: "فارسی (Persian)" },
  { code: "sw", name: "Kiswahili (Swahili)" },
  { code: "ca", name: "Català (Catalan)" },
  { code: "bg", name: "Български (Bulgarian)" },
  { code: "sr", name: "Српски (Serbian)" },
] as const;
